name: pr

on:
  pull_request:

jobs:
  test-image:
    name: Build and test image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --tag nox:test --file Dockerfile

      - name: List content
        run: ls -a
      
      - name: pwd
        run: pwd

      - name: list root
        run: ls /

      - name: list /src
        run: ls /src
        
      - name: Run docker image with python tests
        run: docker run --rm -v ${pwd}:/src nox:test nox -f noxfile.py
