name: Test image on Python code

on:
  pull_request:

  push:
    branches:
      - "master"

jobs:
  test-image:
    name: Build and test image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --tag nox:test --file Dockerfile
      
      - name: Run docker image with python tests
        run: docker run --rm -v ${{ github.workspace }}:/src nox:test nox -f src/noxfile.py
